# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'egel/tmux-gruvbox'

# Bind reload config file to prefix r
bind r source-file ~/.config/tmux/tmux.conf

# Optional: dark or light
set -g @gruvbox 'dark'

# Set true color
set -ga terminal-overrides ",*:Tc"

# Forward focus events to applications inside panes
set -g focus-events on

# Set the status bar to be on top
set -g status-position top

# Set prefix key to NOT be ctrl-b but rather ctrl-Space 
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Always start new windows in the home directory
#set-option -g default-directory "$HOME"

# Always start new windows in the directory I came from
bind c new-window -c "#{pane_current_path}"

# Bind Option-o (or Alt-o) to move between panes
bind -n M-o select-pane -t :.+

# Bind Option-j to split pane horizontally and Option-l to split vertically
bind -n M-j split-window
bind -n M-l split-window -h

# Don't rename windows automatically
set-option -g allow-rename off

# Automatically renumber panes when I close a tab
set -g renumber-windows on

# Use vim copy mode
set -g mode-keys vi
set -g status-keys vi

# Bind Option-k to immediately start scrolling (in copy mode) - and then jump half a page up
# Pressing Option-k repeatedly keeps on moving one page up
# bind -n M-k copy-mode \; send-keys -X halfpage-up

# Bind Option-k to start copy mode
bind -n M-k copy-mode

#
# Initialize TPM (must be at bottom)
run '~/.tmux/plugins/tpm/tpm'

## Override theme
# Make active border pop a bit more
set -g pane-border-style 'fg=#3c3836'
set -g pane-active-border-style 'fg=#fe8019'

set -g pane-border-lines heavy

# Bell notifications
set -g monitor-bell on
set -g bell-action any
set -g window-status-bell-style default
set -g window-status-format "#[bg=colour239 fg=colour237 noitalics]#{?window_bell_flag,#[fg=colour214 bold],#[fg=colour223]} #I  #W#{?window_bell_flag, ⚑,} #[bg=colour237 fg=colour239 noitalics]"
